# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.27.0
import dataclasses
import datetime
from typing import Optional


@dataclasses.dataclass()
class Post:
    post_id: int
    user_id: Optional[int]
    content: str
    post_date: Optional[datetime.datetime]


@dataclasses.dataclass()
class PostRating:
    post_id: int
    user_id: int
    rating: Optional[int]


@dataclasses.dataclass()
class User:
    user_id: int
    username: str
    email: str


@dataclasses.dataclass()
class UserSubscription:
    user_id_a: int
    user_id_b: int
